apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.key
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.crt
  parameters:
    clientID: 168d429f-4320-4b65-8d14-dc7353ea77be
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: kv-aks-p2vdmrywgnliy
    objects: |
      array:
        - |
          objectName: ingress-internal-aks-ingress-contoso-com-tls
          objectType: secret
    tenantID: 888d76fa-54b2-4ced-8ee5-aac1585adee7
